Repository Xaymar/obs-StreamFX, pull requests merged in 2020-09, with the labels that each got.

#283 examples/shaders/transion: Update Luma Burn
  data/examples/shaders/transition/luma-burn.effect
Labels: status:testing-required, type:feature

#327 util/threadpool: Don't hold work endlessly after processing it
  source/util/util-threadpool.cpp
Labels: issue:confirmed, os:linux, os:mac, os:windows, status:tested

#328 ui: Fix support for disambiguation in translations
  source/ui/ui.cpp
Labels: issue:confirmed, os:linux, os:mac, os:windows, status:tested, type:bug-report, type:feature

#345 templates: Fix installation path and 64-bit installations
  templates/installer.iss.in
Labels: os:windows, type:bug-report
